services:
  axonserver:
    hostname: axonserver
    image: axoniq/axonserver:2024.1.4-jdk-17
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true
      - AXONIQ_AXONSERVER_STANDALONE=true
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    volumes:
      - ./db/axonserver/data:/axonserver/data
      - ./db/axonserver/events:/axonserver/events
      - ./db/axonserver/log:/axonserver/log
    networks:
      wallet-accountant: ~

  mongodb:
    image: mongo:7.0.7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=wallet-accountant
    ports:
      - '27017:27017'
    volumes:
      - "./db/mongo:/data/db"
    networks:
      wallet-accountant: ~

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8581:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    networks:
      wallet-accountant: ~
    depends_on:
      - mongodb

networks:
  wallet-accountant: ~