version: "3.8"

services:
  wallet-accountant-karate:
    build:
      context: "."
      dockerfile: docker/prod.dockerfile
    environment:
      - EVENTSTORE_CONNETION_STRING=esdb://eventstore-karate:2113?keepAliveTimeout=10000&keepAliveInterval=10000&tls=false
      - MONGO_CONNECTION_STRING=mongodb://root:example@mongodb-karate:27017/wallet-accountant?authSource=admin&connect=direct
      - FRONTEND_URLS=http://wallet-accountant-ui:3000|ws://wallet-accountant-ui:3000|http://localhost:3000
    stdin_open: true
    tty: true
    depends_on:
      eventstore-available:
        condition: service_completed_successfully
      mongodb-karate:
        condition: service_started
    networks:
      wallet-accountant-karate: ~

  api-available:
    image: alpine:latest
    command: sh -c '/app/wait-for http://wallet-accountant-karate:8080/healthcheck -t 60 -- echo "Api is up!"'
    volumes:
      - "./docker/karate/wait-for:/app/wait-for"
    depends_on:
      wallet-accountant-karate:
        condition: service_started
    networks:
      wallet-accountant-karate: ~

  eventstore-karate:
    image: "eventstore/eventstore"
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
#      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_MEM_DB=True
    volumes:
      - ./dbdata/eventstoreplugins:/usr/share/eventstore/plugins
    networks:
      wallet-accountant-karate: ~

  eventstore-available:
    image: alpine:latest
    command: sh -c '/app/wait-for http://eventstore-karate:2113/health/live -t 0 -- echo "Eventstore is up!"'
    volumes:
      - "./docker/karate/wait-for:/app/wait-for"
    depends_on:
      eventstore-karate:
        condition: service_started
    networks:
      wallet-accountant-karate: ~

  mongodb-karate:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=wallet-accountant
#    ports:
#      - '3085:27017'
    volumes:
      - "./docker/karate/mongo:/docker-entrypoint-initdb.d"
      - type: tmpfs
        target: /data/db
    networks:
      wallet-accountant-karate: ~

  karate:
    image: eclipse-temurin:21-jre
    working_dir: /workdir
    entrypoint: /bin/bash
    command: ./docker/karate/karate.sh
    environment:
      KARATE_CONFIG_ENV: "docker"
      KARATE_CONFIG_MODULE_ROOT: "."
      KARATE_CONFIG_SERVICE: "wallet-accountant-karate"
      KARATE_CONFIG_PORT: "3081"
      STARTUP_WAIT_TIMEOUT: 80
    volumes:
      - .:/workdir
      - ./docker/karate/karate-1.4.1.jar:/app/karate.jar
    container_name: wallet-accountant-karate-runner
    depends_on:
      api-available:
        condition: service_completed_successfully
    networks:
      wallet-accountant-karate: ~

networks:
  wallet-accountant-karate: ~
