spring:
  application:
    name: wallet-accountant
  data:
    mongodb:
      uri: mongodb://localhost:27017/wallet-accountant

axon:
  axonserver:
    servers: localhost:8124

  serializer:
    general: jackson
    messages: jackson
    events: jackson
